

const blogdata = [
    {
      blogId: 1,
      blogHeadline: "Empowering Communities: The Impact of Charitable Giving",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. As we explore the transformative journey brought about by charitable donations, we witness the tangible impact that arises from these acts of generosity. When individuals or organizations contribute to charitable causes, they provide much-needed resources that enable various projects to come to life. From funding educational initiatives and medical missions to supporting disaster relief efforts, these donations serve as a lifeline to communities in need. The monetary support aids in creating sustainable solutions that address underlying issues and foster long-term growth. Consider the story of a small village that lacked access to clean water. Through charitable giving, a water well was constructed, providing the residents with a consistent source of clean and safe water. This not only improved their health and well-being but also empowered them to focus on other endeavors, such as education and economic activities, leading to a self-sustaining community.      ",
      blogCoverImage: "/pic1.jpg",
      blogArticleImages: [""]
    },
    {
      blogId: 2,
      blogHeadline: "Fighting Hunger Together: A Look into Food Drives",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. As we explore the transformative journey brought about by charitable donations, we witness the tangible impact that arises from these acts of generosity. When individuals or organizations contribute to charitable causes, they provide much-needed resources that enable various projects to come to life. From funding educational initiatives and medical missions to supporting disaster relief efforts, these donations serve as a lifeline to communities in need. The monetary support aids in creating sustainable solutions that address underlying issues and foster long-term growth. Consider the story of a small village that lacked access to clean water. Through charitable giving, a water well was constructed, providing the residents with a consistent source of clean and safe water. This not only improved their health and well-being but also empowered them to focus on other endeavors, such as education and economic activities, leading to a self-sustaining community.      ",
      blogCoverImage: "/pic2.jpg",
      blogArticleImages: [""]
    },
    {
      blogId: 3,
      blogHeadline: "Education for All: Transforming Lives through Scholarships",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. As we explore the transformative journey brought about by charitable donations, we witness the tangible impact that arises from these acts of generosity. When individuals or organizations contribute to charitable causes, they provide much-needed resources that enable various projects to come to life. From funding educational initiatives and medical missions to supporting disaster relief efforts, these donations serve as a lifeline to communities in need. The monetary support aids in creating sustainable solutions that address underlying issues and foster long-term growth. Consider the story of a small village that lacked access to clean water. Through charitable giving, a water well was constructed, providing the residents with a consistent source of clean and safe water. This not only improved their health and well-being but also empowered them to focus on other endeavors, such as education and economic activities, leading to a self-sustaining community.      ",
      blogBody2: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. As we explore the transformative journey brought about by charitable donations, we witness the tangible impact that arises from these acts of generosity. When individuals or organizations contribute to charitable causes, they provide much-needed resources that enable various projects to come to life. From funding educational initiatives and medical missions to supporting disaster relief efforts, these donations serve as a lifeline to communities in need. The monetary support aids in creating sustainable solutions that address underlying issues and foster long-term growth. Consider the story of a small village that lacked access to clean water. Through charitable giving, a water well was constructed, providing the residents with a consistent source of clean and safe water. This not only improved their health and well-being but also empowered them to focus on other endeavors, such as education and economic activities, leading to a self-sustaining community.      ",
      blogCoverImage: "/pic1.jpg",
      blogArticleImages: ["/pic1.jpg", "/pic2.jpg", "/pic3.jpg","/pic1.jpg", ]
    },
    {
      blogId: 4,
      blogHeadline: "Healing Hands: Providing Healthcare to Underserved Regions",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. As we explore the transformative journey brought about by charitable donations, we witness the tangible impact that arises from these acts of generosity. When individuals or organizations contribute to charitable causes, they provide much-needed resources that enable various projects to come to life. From funding educational initiatives and medical missions to supporting disaster relief efforts, these donations serve as a lifeline to communities in need. The monetary support aids in creating sustainable solutions that address underlying issues and foster long-term growth. Consider the story of a small village that lacked access to clean water. Through charitable giving, a water well was constructed, providing the residents with a consistent source of clean and safe water. This not only improved their health and well-being but also empowered them to focus on other endeavors, such as education and economic activities, leading to a self-sustaining community.      ",
      blogCoverImage: "/pic4.jpg",
      blogArticleImages: ["./pics/pic10.png", "./pics/pic11.png", "./pics/pic12.png"]
    },
    {
      blogId: 5,
      blogHeadline: "Rescuing Lives: Disaster Relief and Humanitarian Aid",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect.   ",
      blogBody2: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogBody3: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogCoverImage: "/pic5.jpg",
      blogArticleImages: ["/pic3.jpg", "/pic4.jpg", "/pic5.jpg"]
    },
    {
      blogId: 5,
      blogHeadline: "Rescuing Lives: Disaster Relief and Humanitarian Aid",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect.   ",
      blogBody2: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogBody3: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogCoverImage: "/pic5.jpg",
      blogArticleImages: ["/pic3.jpg", "/pic4.jpg", "/pic5.jpg"]
    },
    {
      blogId: 5,
      blogHeadline: "Rescuing Lives: Disaster Relief and Humanitarian Aid",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect.   ",
      blogBody2: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogBody3: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogCoverImage: "/pic5.jpg",
      blogArticleImages: ["/pic3.jpg", "/pic4.jpg", "/pic5.jpg"]
    },
    {
      blogId: 5,
      blogHeadline: "Rescuing Lives: Disaster Relief and Humanitarian Aid",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect.   ",
      blogBody2: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogBody3: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogCoverImage: "/pic5.jpg",
      blogArticleImages: ["/pic3.jpg", "/pic4.jpg", "/pic5.jpg"]
    },
    {
      blogId: 5,
      blogHeadline: "Rescuing Lives: Disaster Relief and Humanitarian Aid",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect.   ",
      blogBody2: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogBody3: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogCoverImage: "/pic5.jpg",
      blogArticleImages: ["/pic3.jpg", "/pic4.jpg", "/pic5.jpg"]
    },
    {
      blogId: 5,
      blogHeadline: "Rescuing Lives: Disaster Relief and Humanitarian Aid",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect.   ",
      blogBody2: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogBody3: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogCoverImage: "/pic5.jpg",
      blogArticleImages: ["/pic3.jpg", "/pic4.jpg", "/pic5.jpg"]
    },
    {
      blogId: 5,
      blogHeadline: "Rescuing Lives: Disaster Relief and Humanitarian Aid",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect.   ",
      blogBody2: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogBody3: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogCoverImage: "/pic5.jpg",
      blogArticleImages: ["/pic3.jpg", "/pic4.jpg", "/pic5.jpg"]
    },
    {
      blogId: 5,
      blogHeadline: "Rescuing Lives: Disaster Relief and Humanitarian Aid",
      blogBody1: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect.   ",
      blogBody2: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogBody3: "Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. Charitable giving has the power to uplift communities, transforming lives and creating a positive ripple effect. ",
      blogCoverImage: "/pic5.jpg",
      blogArticleImages: ["/pic3.jpg", "/pic4.jpg", "/pic5.jpg"]
    },
  ];
  
  export default blogdata;